package cn.edu.whu.dao;

import cn.edu.whu.bean.Access;
import cn.edu.whu.bean.AccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int countByExample(AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int deleteByExample(AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int insert(Access record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int insertSelective(Access record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    List<Access> selectByExample(AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    Access selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Access record, @Param("example") AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Access record, @Param("example") AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Access record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Access record);
}