package cn.edu.whu.dao;

import cn.edu.whu.bean.OperateLogInfo;
import cn.edu.whu.bean.OperateLogInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperateLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int countByExample(OperateLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int deleteByExample(OperateLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int insert(OperateLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int insertSelective(OperateLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    List<OperateLogInfo> selectByExample(OperateLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    OperateLogInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OperateLogInfo record, @Param("example") OperateLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OperateLogInfo record, @Param("example") OperateLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperateLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperateLogInfo record);
}