package cn.edu.whu.bean;

import java.util.Date;

public class OperateLogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.from_ip
     *
     * @mbggenerated
     */
    private String fromIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.operate_func
     *
     * @mbggenerated
     */
    private String operateFunc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.visit_method
     *
     * @mbggenerated
     */
    private String visitMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.method_cost_time
     *
     * @mbggenerated
     */
    private String methodCostTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.log_type
     *
     * @mbggenerated
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.uri
     *
     * @mbggenerated
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.visit_method_error_info
     *
     * @mbggenerated
     */
    private String visitMethodErrorInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.login_out_time
     *
     * @mbggenerated
     */
    private Date loginOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.id
     *
     * @return the value of operate_log_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.id
     *
     * @param id the value for operate_log_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.uid
     *
     * @return the value of operate_log_info.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.uid
     *
     * @param uid the value for operate_log_info.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.uname
     *
     * @return the value of operate_log_info.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.uname
     *
     * @param uname the value for operate_log_info.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.from_ip
     *
     * @return the value of operate_log_info.from_ip
     *
     * @mbggenerated
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.from_ip
     *
     * @param fromIp the value for operate_log_info.from_ip
     *
     * @mbggenerated
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.operate_func
     *
     * @return the value of operate_log_info.operate_func
     *
     * @mbggenerated
     */
    public String getOperateFunc() {
        return operateFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.operate_func
     *
     * @param operateFunc the value for operate_log_info.operate_func
     *
     * @mbggenerated
     */
    public void setOperateFunc(String operateFunc) {
        this.operateFunc = operateFunc == null ? null : operateFunc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.visit_method
     *
     * @return the value of operate_log_info.visit_method
     *
     * @mbggenerated
     */
    public String getVisitMethod() {
        return visitMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.visit_method
     *
     * @param visitMethod the value for operate_log_info.visit_method
     *
     * @mbggenerated
     */
    public void setVisitMethod(String visitMethod) {
        this.visitMethod = visitMethod == null ? null : visitMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.method_cost_time
     *
     * @return the value of operate_log_info.method_cost_time
     *
     * @mbggenerated
     */
    public String getMethodCostTime() {
        return methodCostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.method_cost_time
     *
     * @param methodCostTime the value for operate_log_info.method_cost_time
     *
     * @mbggenerated
     */
    public void setMethodCostTime(String methodCostTime) {
        this.methodCostTime = methodCostTime == null ? null : methodCostTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.log_type
     *
     * @return the value of operate_log_info.log_type
     *
     * @mbggenerated
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.log_type
     *
     * @param logType the value for operate_log_info.log_type
     *
     * @mbggenerated
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.uri
     *
     * @return the value of operate_log_info.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.uri
     *
     * @param uri the value for operate_log_info.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.method
     *
     * @return the value of operate_log_info.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.method
     *
     * @param method the value for operate_log_info.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.visit_method_error_info
     *
     * @return the value of operate_log_info.visit_method_error_info
     *
     * @mbggenerated
     */
    public String getVisitMethodErrorInfo() {
        return visitMethodErrorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.visit_method_error_info
     *
     * @param visitMethodErrorInfo the value for operate_log_info.visit_method_error_info
     *
     * @mbggenerated
     */
    public void setVisitMethodErrorInfo(String visitMethodErrorInfo) {
        this.visitMethodErrorInfo = visitMethodErrorInfo == null ? null : visitMethodErrorInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.status
     *
     * @return the value of operate_log_info.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.status
     *
     * @param status the value for operate_log_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.login_out_time
     *
     * @return the value of operate_log_info.login_out_time
     *
     * @mbggenerated
     */
    public Date getLoginOutTime() {
        return loginOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.login_out_time
     *
     * @param loginOutTime the value for operate_log_info.login_out_time
     *
     * @mbggenerated
     */
    public void setLoginOutTime(Date loginOutTime) {
        this.loginOutTime = loginOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.create_time
     *
     * @return the value of operate_log_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.create_time
     *
     * @param createTime the value for operate_log_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log_info.update_time
     *
     * @return the value of operate_log_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log_info.update_time
     *
     * @param updateTime the value for operate_log_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}